apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "ghcr.io/{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}-{{ .Values.image.os }}-{{ .Values.image.arch }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args:
            - kbot

          env:
            - name: TELE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.TELE_TOKEN.secretName }}
                  key: {{ .Values.TELE_TOKEN.secretKey }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}