apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kbot
  namespace: default

spec:
  project: default

  source:
    repoURL: https://github.com/visys-dev/kbot.git
    targetRevision: develop
    path: kbot

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true