replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "visys-dev/kbot"
  tag: "v1.0.2-28-g43edecb"
  os: linux
  arch: amd64
  pullPolicy: IfNotPresent
TELE_TOKEN:
  secretName: "kbot"
  secretKey: "token"
resources: {}
securityContext:
  allowPrivilegeEscalation: false
