name: KBOT-CI/CD

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "kbot/values.yaml"

permissions:
  contents: write
  packages: write


env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  OS: linux
  ARCH: amd64

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: Set VERSION
        run: |
          VERSION="$(git describe --tags --always)"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION"

      - name: Login to GHRC
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: make image
      - name: Push image
        run: make push

  cd:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Set VERSION
        run: |
          VERSION="$(git describe --tags --always)"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION"

      - name: Update Helm image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = strenv(VERSION)' kbot/values.yaml

      - name: Commit Helm version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kbot/values.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update kbot image to $VERSION"
          git push origin develop